######################## default configuration ####################
baseURL = "https://eesev9ie.github.io/"
title = "Georg-Cantor-Gymnasium"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [""] # desable language from here
defaultContentLanguageInSubdir = true

defaultContentLanguage = "de"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Schule"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "Schule"
  name = "Über die Schule"
  URL = "about"
  weight = 1

  [[menu.main]]
  parent = "Schule"
  name = "Ganztagsangebote"
  URL = "ganztagsangebote"
  weight = 2

  [[menu.main]]
  parent = "Schule"
  name = "Termine"
  URL = "event"
  weight = 3

  [[menu.main]]
  parent = "Schule"
  name = "Lehrer und AG-Leiter"
  URL = "teacher"
  weight = 4

  [[menu.main]]
  parent = "Schule"
  name = "Wettbewerbe"
  URL = "wettbewerbe"
  weight = 5

  [[menu.main]]
  parent = "Schule"
  name = "CantorPreis"
  URL = "cantorpreis"
  weight = 6

  [[menu.main]]
  parent = "Schule"
  name = "Anmeldung"
  URL = "anmeldung"
  weight = 7

  [[menu.main]]
  parent = "Schule"
  name = "Schulchronik"
  URL = "schulchronik"
  weight = 8

[[menu.main]]
weight = 2
name = "Digitale Angebote"
hasChildren = true

  [[menu.main]]
  parent = "Digitale Angebote"
  name = "Vertretugsplan"
  URL = "https://stundenplan24.de/20072021/mobil"
  weight = 1

  [[menu.main]]
  parent = "Digitale Angebote"
  name = "Lernplattform Moodle"
  URL = "https://moodle.bildung-lsa.de/gcg"
  weight = 2

[[menu.main]]
name = "Für Schüler und Eltern"
weight = 3
hasChildren = true

  [[menu.main]]
  parent = "Für Schüler und Eltern"
  name = "Formulare und Vorlagen"
  URL = "forms"
  weight = 1

  [[menu.main]]
  parent = "Für Schüler und Eltern"
  name = "Förderverein"
  URL = "https://www.cantor-foerderverein.de"
  weight = 2

  [[menu.main]]
  parent = "Für Schüler und Eltern"
  name = "Schulshop"
  URL = "https://schulkleidung.de/shop/index.php?nr=SDQUCKVD"
  weight = 4

  [[menu.main]]
  parent = "Für Schüler und Eltern"
  name = "Schülerrat"
  URL = "schuelerrat"
  weight = 3

  [[menu.main]]
  parent = "Für Schüler und Eltern"
  name = "Hinweise"
  URL = "notice"
  weight = 5

[[menu.main]]
name = "Aktuelles"
URL = "blog"
weight = 4

[[menu.main]]
name = "Kontakt"
URL = "contact"
weight = 5


# footer menu

[[menu.footer]]
name = "Lehrer und AG-Leiter"
URL = "teacher"

[[menu.footer]]
name = "Informationen"
URL = "notice"

[[menu.footer]]
name = "Termine"
URL = "event"

[[menu.footer]]
name = "Anmeldung"
URL = "anmledung"

[[menu.footer]]
name = "Formulare und Vorlagen"
URL = "forms"


#################### default parameters ################################
[params]
logo = "media/logo.png"
# Meta data
author = "Denys Konovalov|CantorTechnik AG|LXDB Team"
# contact info
address = "Georg-Cantor-Gymnasium, Torstraße 13, 06110 Halle(Saale)"
route_link = "https://maps.openrouteservice.org/directions?n1=51.473292&n2=11.965606&n3=18&a=null,null,51.473292,11.965606&b=0&c=0&k1=de&k2=km"
mobile = "+49345 6903156"
email = "schulleitung@cantor-gymnasium.de"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "media/logo.png" # use jpg, png, svg or gif format.

# Subscription
##[params.subscription]
#enable = false
# mailchimp subsciption
#mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
#mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

############################# social site ########################
[[params.social]]
title = "YouTube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCHafBDI5qfK03RiIEyki9VA"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/eesev9ie"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Georg-Cantor-Gymnasium Halle"

impressumURL = "impressum"

################################### German language #####################################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 2
home = "Startseite"
# copyright
copyright = "Copyright &copy; 2020 Georg-Cantor-Gymnasium Halle(Saale)"

impressumURL = "impressum"
